# Generated by Django 3.1.2 on 2021-01-02 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210102_2311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='catategory',
            new_name='category',
        ),
    ]
