# Generated by Django 3.1.2 on 2021-01-03 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210102_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=0, max_length=12),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default='news', on_delete=django.db.models.deletion.CASCADE, to='blog.category'),
        ),
    ]
